# General
title: steilerPhoto

# Local server settings
host: 0.0.0.0


## Permalink for blog posts
permalink: /:year/:month/:title/

# Build settings
markdown: kramdown
incremental: true
gems:
  - jekyll-assets
  - jekyll-sitemap
  - jekyll-last-modified-at
  - octopress-paginate

include: 
  - _pages
  - _files

exclude:
  - steilerPhoto
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - _posts/README.md
  - _pages/README.md
  - _files/README.md

excerpt_separator: <!--more-->

picture_generator:
    extension: ".jpg"
    source: "_images"
    cache: "_images/.cache"

compress_html:
    clippings: all
    comments: ["<!-- ", " -->"]
    endings: all
    blanklines: false
    profile: false
    startings: all

# Purify CSS
purify:
    compress: true
    force_class:
        - 'social-button-reddit'
        - 'social-button-email'
        - 'hoverEffect'
        - 'col-sm-8'
        - 'desc-container'
        - 'col-sm-4'
        - 'img-container'

compress_files:
    compressions: 
        - 'gzip'
        - 'brotli'
    file_types:
        - 'json'
        - 'ttf'
        - 'xml'
        - 'woff'
        - 'css'
        - 'js'
        - 'tff'
        - 'eot'
        - 'html'
        - 'svg'
    

# Remove unnecessary CSS and JS
clean: true

#
# Deploy settings
#

deploy:
- rsync -az --delete ./ FrankSteiler@steilerphoto.de:/var/www/steilerPhoto/

#
# jekyll-assets config
# 

assets:
    compress:
        css: true
        js: true

    autowrite: true
    cache_type: memory

    prefix: "/assets"
    digest: true
    
    sources: 
        - _assets/favicon

    assets:
        # Copy all files withtin the _assets folder structure to the /assets/ folder and give them a digest
        - "*"

    features:
        liquid: false
        automatic_img_size: false
        automatic_img_alt: false
